# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

tasks:
  - name: Install PLCC
    command: |
      echo ''
      echo 'export LIBPLCC="$GITPOD_REPO_ROOT/src"
      export PATH="$LIBPLCC:$PATH"
      ' >> "$HOME/.bashrc"
      exec bash
  - name: Update Java
    command: sdk install java < /dev/null