# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

tasks:
  - name: Install Dev Environment
    command: |
      echo "INSTALLING latest JAVA (a PLCC dependency)"
      sdk install java < /dev/null
      echo ""
      echo "INSTALLING PLCC in $GITPOD_REPO_ROOT/src"
      echo 'export LIBPLCC="$GITPOD_REPO_ROOT/src"
      export PATH="$LIBPLCC:$PATH"
      ' >> "$HOME/.bashrc"
      echo ""
      echo "INSTALLING reuse (for licenses: https://reuse.software/)"
      pip install --upgrade pip
      pip install pipx
      pipx install reuse
      echo ""
      echo "INSTALLING ag (for searching: https://github.com/ggreer/the_silver_searcher)"
      sudo apt-get update
      sudo apt-get --no-install-recommends install silversearcher-ag
      echo ""
      echo "INSTALLING bats (for testing: https://bats-core.readthedocs.io/en/latest/index.html)"
      export BATS_VERSION=v1.11.0 \
        && sudo apt-get update \
        && sudo apt-get install -y \
            git \
        && sudo apt-get clean \
        && sudo rm -rf /var/lib/apt/lists/* \
        && sudo git clone https://github.com/bats-core/bats-core.git \
        && cd bats-core \
        && sudo git checkout $BATS_VERSION \
        && sudo ./install.sh /usr/local \
        && cd .. \
        && sudo rm -rf bats-core
      exec bash
