#!/bin/bash

[ -d Java ] || {
    echo "Java directory missing" >&2
    exit 1
}

[ -f Java/Parse.class ] || {
    echo "Java/Parse.class missing" >&2
    exit 2
}

if [ echo "$*" | grep "--json" ]; 
then 
    javac -cp .:jackson-annotations-2.15.2.jar:jackson-core-2.15.2.jar:jackson-databind-2.15.2.jar *.java
    java -cp ./Java:jackson-annotations-2.15.2.jar:jackson-core-2.15.2.jar:jackson-databind-2.15.2.jar ParseJSONAST $*
else 
    java -cp ./Java Parse $*
fi
