#!/bin/bash

JACKSON_VERSION="2.15.2"
JACKSON_ANNOTATIONS="${LIBPLCC}/lib/jackson-annotations-${JACKSON_VERSION}.jar"
JACKSON_CORE="${LIBPLCC}/lib/jackson-core-${JACKSON_VERSION}.jar"
JACKSON_DATABIND="${LIBPLCC}/lib/jackson-databind-${JACKSON_VERSION}.jar"
CP="${JACKSON_ANNOTATIONS}:${JACKSON_CORE}:${JACKSON_DATABIND}"

[ -d Java ] || {
    echo "Java directory missing" >&2
    exit 1
}

[ -f Java/Parse.class ] || {
    echo "Java/Parse.class missing" >&2
    exit 2
}

if  echo "$*" | grep -- "--jsonast" &> /dev/null
then

    ARGS=()
    while [ $# -gt 0 ] ; do
        case "$1" in
            --json)
                shift
            ;;
            *)
                ARGS+=("$1")
                shift
            ;;
        esac
    done

    java -cp "./Java:${CP}" ParseJsonAst "${ARGS[@]}"
else 
    java -cp ./Java Parse $*
fi
