#!/bin/bash

LIB="${LIBPLCC:-/usr/local/pub/plcc/PLCC}"
PYTHON3=python3
PLCC="$LIB/plcc.py"

if [ "$1" = "-c" ];
then
        rm Java/*.java Java/*.class &>/dev/null
        shift
fi

if [ $# -gt 0 ];
then
        FILES="$@"
else
        FILES="${FILE:-grammar}"
fi

[ -d "$LIB" ] || {
        echo "$LIB: no such directory" >&2
        exit 1
}

$PYTHON3 "$PLCC" $FILES || {
        echo "cannot compile $FILES" >&2
        exit 4
}

[ -d Java ] || {
        echo "Java directory missing" >&2
        exit 5
}

(cd ./Java ; javac *.java)
