---
# yamllint disable line-length
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: codfish/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
          additional-packages: |
            ['conventional-changelog-conventionalcommits']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/ourplcc/plcc
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          context: .
          file: ./containers/plcc/Dockerfile
          push: true
          # yamllint disable-line rule:line-length
          tags: |
            ghcr.io/ourplcc/plcc:${{ steps.semantic.outputs.release-version }}
            ghcr.io/ourplcc/plcc:${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}
            ghcr.io/ourplcc/plcc:${{ steps.semantic.outputs.release-major }}
            ghcr.io/ourplcc/plcc:latest
          platforms: linux/amd64,linux/arm64
