# Copyright (C) 2022 vscode
#
# This file is part of LibreFoodPantry.
#
# LibreFoodPantry is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LibreFoodPantry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LibreFoodPantry.  If not, see <http://www.gnu.org/licenses/>.

---
# yamllint disable line-length
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: docker://ghcr.io/codfish/semantic-release-action@sha256:cfb2b8231400c4bcb0abb8403c38aaff0c865e1bae8892b9b40893db9ef49403
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/github'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/ourplcc/plcc
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          context: .
          file: ./shell/Dockerfile
          push: true
          # yamllint disable-line rule:line-length
          tags: |
            ghcr.io/ourplcc/plcc:${{ steps.semantic.outputs.release-version }}
            ghcr.io/ourplcc/plcc:${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}
            ghcr.io/ourplcc/plcc:${{ steps.semantic.outputs.release-major }}
            ghcr.io/ourplcc/plcc:latest
          platforms: linux/amd64,linux/arm64
