---
name: test_python-max_java-max

on:
  pull_request:

jobs:
  build:
    name: test_python-max_java-max
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
      -
        name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./containers/configurable/Dockerfile
          tags: test-image:latest
          push: false
      -
        name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: |
            source /home/tester/.sdkman/bin/sdkman-init.sh
            python3 --version
            python --version
            java --version
            javac --version
            /home/tester/.plcc/bin/test/functionality.bash
          shell: bash
