---
name: test_python-3.9.19_Java-11.0.21-tem

on:
  pull_request:

jobs:
  build:
    name: test_python-3.9.19_Java-11.0.21-tem
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./containers/configurable/Dockerfile
          tags: test-image:latest
          push: false
          build-args: |
            JAVA_VERSION=11.0.21-tem
            PYTHON_VERSION=3.9.19
      -
        name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: |
            source /home/tester/.sdkman/bin/sdkman-init.sh
            python3 --version
            python --version
            java --version
            javac --version
            /home/tester/.plcc/bin/test/functionality.bash
          shell: bash
