---
name: Test with (Python, Java) = (max, max)

on:
  pull_request:

jobs:
  build:
    name: Test with (Python, Java) = (max, max)
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./shell/test.dockerfile
          tags: test-image:latest
          push: false
      -
        name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: /plcc/tests/run
